- name: Set hosts
  copy:
    dest: /etc/hosts
    content: |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      {{ ip }} {{ fqdn }} {{ hostname }}
- name: Set hostname
  shell: hostnamectl set-hostname {{ hostname }}
